set filetype=on
syntax on
set nocompatible
set bs=2
set wrapmargin=8
set ruler
set nu
set smartindent
set tabstop=2 shiftwidth=2 expandtab

set background=dark
colorscheme darkblue

set backupdir=/tmp/
set directory=/tmp/

set iskeyword+=58
